[package]
authors = ["akimasa-l <liumingzheng8@outlook.com>"]
edition = "2018"
name = "loops"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.3"
